resources:
  - id: dep-file
    type: file
    depends_on: [base-git] # Dependency across files!
    parameters:
      path: /tmp/veto-mod-test/dep.txt
      content: "I depend on base-git"
      state: present
